### ISSUE TITLE
release of 1.9?

### ISSUE THREAD

**Issue by jrmarino** [stcarrez/ada-util#1]
Hi Stephane,
I've been keeping my eye on this to see when 1.9 is released (hopefully with a git tag so that it shows in github as a release).  Do you have any idea when that might happen?

**Comment by stcarrez** [comment]
I was busy to work on the EtherScope submission to the Make with Ada competition...
I still have some work on the XML/JSON serialization framework for the XML/JSON API support in Ada Server Faces. This was my summer work in Spain but I've not finished it yet...

**Comment by stcarrez** [comment]
After nearly 2 years, I finally made it.

Release 1.9 is out. I hope and wish I could release more often in the future...
