### ISSUE TITLE
util-http-clients-curl.ads missing after installation

### ISSUE THREAD

**Issue by S0me6uy** [stcarrez/ada-util#15]
Hello,

i'm encountering a strange issue : 
`file "util-http-clients-curl.ads" not found
"Util" is not visible`

I use successfully this list of commands to install ada-util, and all worked well without error :

`git clone --recursive https://github.com/stcarrez/ada-util.git

cd ada-util
./configure  --prefix=/usr

sudo make

sudo make test

sudo bin/util_harness
(1 error but i guess no connexion with my problem :
`
Test Util.Dates.Formats.Format - util-dates-formats-tests.adb:90: Invalid result for: %j: expecting '323' value was '322' FAIL     0.000541000s`

`Test Util.Dates.RFC7231.Append_Date - util-dates-formats-tests.adb:443: Invalid date conversion: expecting 'Wed, 07 Oct 2015 03:41:11 GMT' value was 'Tue, 07 Oct 2015 03:41:11 GMT' FAIL     0.000505000s`)
        
sudo make install`

I'm working on Ada with GPS, and when i open my project, no error is raised, so ada-util seems to be well found by GPS.
Do you have any idea ?
It was working by start of july.

**Comment by stcarrez** [comment]
I guess this is because the curl library was not found when you ran the `.configure` script.

If you look at `ada-util/utilada_conf.gpr`, you should see a set of lines, if the configure was ok you should see:

```
   Xml_Version : Xml_Version_Type := "4";
   Has_Curl    : Config.Yes_No := "yes";
   Has_AWS     : Config.Yes_No := "yes";
   Has_Xml     : Config.Yes_No := "yes";
   Has_Lzma    : Config.Yes_No := "yes";
```

If you see `no` to the `Has_Curl`, it means it was not found by configure.
You should install the libcurl development library with C headers.
On Ubuntu 20, it's provided by the package `libcurl4-openssl-dev`.

By the way, why are you running the build command as `sudo`?
It's not a good practice to build as root.

**Comment by S0me6uy** [comment]
Thank you for your response : It was exactly that.
i guess i used before some packets which installed by default libcurl4-openssl-dev so there was no issue.

I'm sorry, i've just found your wiki installation note where it's mentionned ...
Next time i'll search and watch for wiki and notes in first

And about using sudo with configure, i tried it by fear of needed packets couldn't be reached by low level user, but i never use it otherwise

**Comment by OnofreTZK** [comment]
Hi, I'm pretty new to the language and the package manager `Alire`.

I'm having the same problem when I try `alr run` after adding `with Util.Http.Clients.Curl;` to my project:

![Screenshot 2023-06-13 at 17 12 33](https://github.com/stcarrez/ada-util/assets/38487230/040a4fbd-6ee9-4d9d-9c9d-956e2d6b033d)

I did install it as the [Alire Docs](https://alire.ada.dev/docs/#dependencies-and-upgrading) specify.


-----


```bash
# Curl version
curl-config --version
libcurl 8.1.2

# Alire version
 alr version
APPLICATION
alr version:               1.2.2
libalire version:          1.2.2
compilation date:          2023-01-12 20:52:40
compiler version:          Community 2020 (20200818-84)
```
OS:  macos Ventura 13.0.1 
Arch: arm64

Could you guys help me?

**Comment by stcarrez** [comment]
Have you tried adding the following line at beginning of your GNAT project:

```
with "utilada_curl";
```

**Comment by OnofreTZK** [comment]
Worked! thanks for the help!
