### ISSUE TITLE
Typo in procedure name

### ISSUE THREAD

**Issue by jquorning** [stcarrez/ada-util#26]
The private procedure `Elligible_Files` in `Util.Files.Rolling`. Should it be `Eligible_Files` of `Illigeble_Files`?

**Comment by stcarrez** [comment]
It should be `Eligible_Files`. It's goal is to select files that are eligible to a rollover and cleanup.

Interesting that the word `eligible` is a French word that I'm not able to spell correctly!

**Comment by jquorning** [comment]
I have to look up the word every time to get the correct sequence of e's and i's :-)
