### ISSUE TITLE
Windows 10, problems

### ISSUE THREAD

**Issue by ohenley** [stcarrez/ada-util#3]
**1) config.guess and config.sub hand out with ada-util are outdated:**

$ ./configure --disable-ahven --disable-curl --disable-aws
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2002-02-19, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

    ftp://ftp.gnu.org/pub/gnu/config/

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

**2) After updating to latest config.guess and config.sub from ftp://ftp.gnu.org/pub/gnu/config/, configure passes but make is not going through:**

$ make
/usr/bin/make UTIL_LIBRARY_TYPE=static build build-test
make[1]: Entering directory `/d/ShillBig/gnoga-code-1.2b/deps/ada-util'
gprbuild -m -p -P"util.gpr" -XMODE=debug -XCOVERAGE=no -XUTIL_LIBRARY_TYPE=stati                                  c -XPROCESSORS=4 -XHARDWARE_PLATFORM=unknown
Compile
   [Ada]          util-processes-os.adb
   [Ada]          util-http.adb
   [Ada]          util-http-tools.adb
   [Ada]          util-http-rest.adb
util-processes-os.ads:24:09: type must be declared abstract or "Stop" overridden
util-processes-os.ads:24:09: "Stop" has been inherited from subprogram at util-p                                  rocesses.ads:172

   compilation of util-processes-os.adb failed

gprbuild: *** compilation phase failed
make[1]: *** [build] Error 4
make[1]: Leaving directory `/d/ShillBig/gnoga-code-1.2b/deps/ada-util'
make: *** [static] Error 2

**I tapped into util.gpr to specify "os-win32" for Os_Version and Os_Src_Dir and build using gprbuild directly inside GPS. It worked.**

Note: For example I am only interested in JSON serial/deserial. Maybe would it be possible to split the utils in more specific target eg. util-core, util-json, util-xml etc?

**Comment by stcarrez** [comment]
I guess the last issue is an x64 issue as the *-pc-mingw64 was not recognized as a platform.
I've integrated latest versions of config.sub and config.guess and update the configure to recognize the mingw64 hoping this will fix your issue.

I'll try to introduce configure options to enable/disable some features.

**Comment by ohenley** [comment]
I re-cloned, then build from scratch and it works like a charm. You can close this issue.
Merci.

**Comment by stcarrez** [comment]
Thanks!
