### ISSUE TITLE
utilada_aws: raised PROGRAM_ERROR : SSL not supported.

### ISSUE THREAD

**Issue by ethindp** [stcarrez/ada-util#33]
@stcarrez I'm unsure if this is a bug on Utilada's end or not but it appears to be so. When I try to download content via HTTPS, this exception is thrown. I'm unsure how to enable TLS through utilada and I don't know if there's something I'm missing or not. Is this indeed a bug as I think it is?

**Comment by stcarrez** [comment]
This exception means the Ada Web Server does not have SSL support.

I'm using the following piece of code to check whether SSL is supported by AWS:

```
   Log    : constant Util.Log.Loggers.Logger := Util.Log.Loggers.Create ("Auth_Demo");
...
   if not AWS.Net.SSL.Is_Supported then
      Log.Error ("SSL is not supported by AWS.");
      Log.Error ("SSL is required for the OpenID connector to connect to OpenID providers.");
      Log.Error ("Please, rebuild AWS with SSL support.");
      return;
   end if;
```

**Comment by ethindp** [comment]
I think that I've managed to solve this issue -- thank you.
