### ISSUE TITLE
Alire lost reference to `utils-streams-buffered-parts.ads`

### ISSUE THREAD

**Issue by OnofreTZK** [stcarrez/ada-util#45]
I was following the sample for sending multipart data and it was working until I start working on my project the next day and got this message:

```bash
service.adb:7:06: error: file "util-streams-buffered-parts.ads" not found
```
I did change nothing from yesterday, I just tried `alr run` as usual (even before writing something new in the code) and this happened.

**Comment by stcarrez** [comment]
The `Util.Streams.Bufferd.Parts` package is only available with the 2.6.0 version or the git version.

The Alire package is not yet updated so it is still based on the 2.5.0 version.

I´m in the process of doing a release in the next days, so the 2.6.0 will come soon.

In the meantime you may try to pin the version with Alire but I´m not familiar with this technic....

**Comment by OnofreTZK** [comment]
Got it, it is a personal project so I don't mind waiting a bit.

Thanks for clarifying!

**Comment by stcarrez** [comment]
Ada Utility Library 2.6.0 was integrated as new official crate in August 2023.
