### ISSUE TITLE
AdaUtils cannot be built with msys2 64bits in windows 10

### ISSUE THREAD

**Issue by badger1961** [stcarrez/ada-util#5]
Hello

I tried to build this package with  msys2 (64 bits) in Windows 10. My steps is the following 
- Run msys2 bash
- Run ./configure
- Run make

While compilation I observe the following error
gprbuild -m -q -p -Putilada_core.gpr -XHARDWARE_PLATFORM=unknown -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=4 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_base.gpr -XHARDWARE_PLATFORM=unknown -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=4 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_sys.gpr -XHARDWARE_PLATFORM=unknown -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=4 -XUTIL_LIBRARY_TYPE=static
util-processes-tools.adb:19:06: file "util-systems-os.ads" not found

   compilation of util-processes-tools.adb failed

gprbuild: *** compilation phase failed
make: *** [Makefile:32: static] Error 4

The file util-systems-os.ads exists. The windows version can be found in 
src/sys/processes/os-win32

I think that corresponded option regarding compilation under Windows 64 bits is not set.
Are there ways to set up this option correctly?

Thanks
Alexander

**Comment by stcarrez** [comment]
Looks strange.  I was able to build on Windows 10 x64 with GNAT 2019.

If you look at utilada_sys.gpr, you should see the line:

> Os_Version  : Os_Version_Type := "windows";

If the os-win32 files are not found, may by the value you have for Os_Version is not "windows".
What values do you have for it?

What is the output when you run the following command:

> ./config.guess

**Comment by badger1961** [comment]
I see, this is msys2's trick ./config.guess returns : x86_64-pc-msys
What is your way to build under Windows? Do you use mingw or msys or msys2?

**Comment by stcarrez** [comment]
Thanks.

I'm using mingw for Windows32 but I've installed msys2 for Windows10/x64.

For me the config.guess returns x86_64-pc-mingw64
But looking at config.guess, the -msys case can also happen.

Let me know if you have problems.

**Comment by badger1961** [comment]
Thanks. Right now utilada_sys.gpr contains correct version of. It is  Os_Version  : Os_Version_Type := "windows";
But I observed the following compilation error : 

gprbuild -m -q -p -Putilada_core.gpr -XHARDWARE_PLATFORM=unknown -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=4 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_base.gpr -XHARDWARE_PLATFORM=unknown -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=4 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_sys.gpr -XHARDWARE_PLATFORM=unknown -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=4 -XUTIL_LIBRARY_TYPE=static
util-systems-os.ads:58:40: "HANDLE" not declared in "Types"
util-systems-os.ads:80:42: expected type "File_Type" defined at util-systems-types.ads:29
util-systems-os.ads:80:42: found private type "System.Address"
util-systems-os.ads:193:55: "Stat_Type" not declared in "Types"
util-systems-os.ads:197:56: "Stat_Type" not declared in "Types"
util-systems-os.ads:58:40: "HANDLE" not declared in "Types"
util-systems-os.ads:80:42: expected type "File_Type" defined at util-systems-types.ads:29
util-systems-os.ads:80:42: found private type "System.Address"
util-systems-os.ads:193:55: "Stat_Type" not declared in "Types"
util-systems-os.ads:197:56: "Stat_Type" not declared in "Types"
util-streams-raw.adb:22:09: warning: unit "Ada.Text_IO" is not referenced
util-streams-raw.adb:35:22: operator for type "File_Type" defined at util-systems-types.ads:29 is not directly visible
util-streams-raw.adb:35:22: add with_clause and use_clause for "Raw"
util-streams-raw.adb:65:22: operator for type "File_Type" defined at util-systems-types.ads:29 is not directly visible
util-streams-raw.adb:65:22: add with_clause and use_clause for "Raw"
util-systems-os.ads:58:40: "HANDLE" not declared in "Types"
util-systems-os.ads:80:42: expected type "File_Type" defined at util-systems-types.ads:29
util-systems-os.ads:80:42: found private type "System.Address"
util-systems-os.ads:193:55: "Stat_Type" not declared in "Types"
util-systems-os.ads:197:56: "Stat_Type" not declared in "Types"
util-processes-os.adb:83:07: warning: possibly useless assignment to "Result", value might not be referenced
util-processes-os.adb:91:07: warning: use clause for package "Raw" has no effect
util-processes-os.adb:92:07: warning: use clause for package "Conversions" has no effect
util-processes-os.adb:93:07: warning: use clause for package "C" has no effect
util-processes-os.adb:195:07: warning: useless assignment to "Result", value overwritten at line 197
util-processes-os.adb:248:07: warning: possibly useless assignment to "Result", value might not be referenced
util-processes-os.adb:311:07: warning: use clause for private type "System.Address" has no effect
util-systems-os.ads:58:40: "HANDLE" not declared in "Types"
util-systems-os.ads:80:42: expected type "File_Type" defined at util-systems-types.ads:29
util-systems-os.ads:80:42: found private type "System.Address"
util-systems-os.ads:193:55: "Stat_Type" not declared in "Types"
util-systems-os.ads:197:56: "Stat_Type" not declared in "Types"

   compilation of util-processes-os.adb failed
   compilation of util-streams-raw.adb failed
   compilation of util-systems-dlls.adb failed
   compilation of util-systems-os.ads failed

gprbuild: *** compilation phase failed
make: *** [Makefile:32: static] Error 4

**Comment by stcarrez** [comment]
I see the issue. I've not installed the gcc compiler which comes with msys.
I'm using the gcc that GNAT 2019 provides. They don't have the same compilation flags.
The msys gcc does not define _WIN32 as GNAT gcc does.

I'll fix the build shortly.

**Comment by badger1961** [comment]
Thanks. I'm able to build on the latest baseline. Samples can be built and run as well

**Comment by stcarrez** [comment]
Closing because we can build in Windows 10 64-bits.
