### ISSUE TITLE
make test fails on debian stretch

### ISSUE THREAD

**Issue by devosalain** [stcarrez/ada-util#7]
configure and make runs fine.
But make test produces on my system,
root@emiel:/home/y/ada-util/ada-util-master# make test
gprbuild -m -q -p -Putilada_core.gpr -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_base.gpr -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_sys.gpr -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_unit.gpr -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_http.gpr -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Ptests_proc -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8
gprbuild -m -q -p -Putilada_tests -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8
bin/util_harness -l utilada: -xml util-aunit.xml -timeout 30
Usage: test <exit-code> <mode> <data>
b
c
d
e
f
  Systems.Dlls:
   Test Util.Systems.Dlls.Load - util-systems-dlls-tests.adb:68: At least on Load operation should have failedreturned null FAIL     0.000335000s
   Test Util.Systems.Dlls.Get_Symbol - util-systems-dlls-tests.adb:68: At least on Load operation should have failedreturned null FAIL     0.000291000s
utilada:        Tests run: 271, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 7.823453000
Makefile:63: recipe for target 'test' failed
make: [test] Error 1 (ignored)
root@emiel:/home/y/ada-util/ada-util-master#

**Comment by stcarrez** [comment]
The test tries to load libcrypto.so which means that we have an hidden dependency with openssl.

**Comment by devosalain** [comment]
Ok, this time I have :
utilada:        Tests run: 273, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.176468000
which looks good.
