### ISSUE TITLE
make fails on FreeBSD ala.ala 12.1-RC1

### ISSUE THREAD

**Issue by devosalain** [stcarrez/ada-util#8]
config.status: creating utilada_lzma.gpr
config.status: creating utilada_tests.gpr
/home/x/ada-util-master %make                                                                                                                  19-10-27 1:42
make: "/fbsd2/usr/home/x/ada-util-master/Makefile" line 11: Missing dependency operator
make: "/fbsd2/usr/home/x/ada-util-master/Makefile" line 13: Need an operator

**Comment by stcarrez** [comment]
On FreeBSD and NetBSD, you must use gmake and not make.

**Comment by devosalain** [comment]
--------------------------------------
`
Right , 
configure looks ok : 
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pandoc... yes
checking for dynamo... no
checking build system type... x86_64-unknown-freebsd12.1
checking host system type... x86_64-unknown-freebsd12.1
checking target system type... x86_64-unknown-freebsd12.1
checking for a BSD-compatible install... /usr/bin/install -c
checking for gprbuild... gprbuild
checking for gprclean... gprclean
checking for gprinstall... gprinstall
checking whether make sets $(MAKE)... yes
checking whether ln -s works... yes
checking shared library support... no
checking default library type... static
checking distribution build... yes
checking coverage support... no
checking number of processors... 8
checking preparing for GNAT project utilada_core... done
checking preparing for GNAT project utilada_base... done
checking preparing for GNAT project utilada_sys... done
checking operating system... freebsd
checking hardware platform... x86_64
checking whether platform supports atomic inc/dec... yes
checking specific processor support... using intrinsic
checking whether utilgen support is required... no
checking whether directories project exists... no
checking whether xmlada_sax project exists... no
checking whether xmlada project exists... no
checking XML/Ada version... none
checking Ada LZMA Library... 
checking traceback in log exceptions... yes
checking whether AUnit support is enabled... no
checking whether Ahven internal support is enabled... yes
checking curl HTTP client support in Ada Util... yes
checking for curl_easy_perform in -lcurl... yes
checking preparing for GNAT project utilada_curl... done
checking AWS support is enabled... yes
checking whether aws project exists... no
checking checking AWS version... none
checking using AWS http client... 1
checking for gcc bug compiling Util.Serialize.Mappers.Vector_Mappers (Bug 53737)... no
checking whether the Util.Serialize.Mappers.Vector_Mappers package must be compiled... yes
checking for additional linker options for libutilada... none
checking for additional linker options for libutilada_curl... none
checking installation of Ada source files... <prefix>/include
checking installation of Ada ALI files... <prefix>/lib
checking installation of library files... <prefix>/lib
checking installation of GNAT project files... <prefix>/lib/gnat
configure: creating ./config.status
config.status: creating Makefile.conf
config.status: creating utilada.gpr
config.status: creating utilada_http.gpr
config.status: creating utilada_unit.gpr
config.status: creating utilada_curl.gpr
config.status: creating utilada_aws.gpr
config.status: creating utilada_core.gpr
config.status: creating utilada_base.gpr
config.status: creating utilada_sys.gpr
config.status: creating utilada_lzma.gpr
config.status: creating utilada_tests.gpr
----------------------------------------------------
But gmake produces :

mkdir -p obj/utilada_core/static
mkdir -p obj/utilada_base/static
mkdir -p obj/utilada_sys/static
mkdir -p obj/utilada_curl/static
mkdir -p obj/utilada_unit/static
mkdir -p obj/utilada_http/static
gprbuild -m -q -p -Putilada_core.gpr -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_base.gpr -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8 -XUTIL_LIBRARY_TYPE=static
gprbuild -m -q -p -Putilada_sys.gpr -XHARDWARE_PLATFORM=x86_64 -XMODE=distrib -XCOVERAGE=no -XPROCESSORS=8 -XUTIL_LIBRARY_TYPE=static
util-systems-types.ads:65:27: warning: 640 bits of "Stat_Type" unused
util-serialize-io-xml.adb:19:06: file "unicode.ads" not found
util-serialize-io-xml.adb:20:06: file "unicode-ces-utf8.ads" not found
util-serialize-io-xml.ads:19:06: file "sax.ads" not found
util-serialize-io-xml.ads:19:06: "Util.Serialize.Io.Xml (body)" depends on "Util.Serialize.Io.Xml (spec)"
util-serialize-io-xml.ads:19:06: "Util.Serialize.Io.Xml (spec)" depends on "Sax (spec)"
util-serialize-io-xml.ads:20:06: file "sax.ads" not found
util-serialize-io-xml.ads:20:06: "Util.Serialize.Io.Xml (body)" depends on "Util.Serialize.Io.Xml (spec)"
util-serialize-io-xml.ads:20:06: "Util.Serialize.Io.Xml (spec)" depends on "Sax (spec)"
util-serialize-io-xml.ads:21:06: file "sax.ads" not found
util-serialize-io-xml.ads:21:06: "Util.Serialize.Io.Xml (body)" depends on "Util.Serialize.Io.Xml (spec)"
util-serialize-io-xml.ads:21:06: "Util.Serialize.Io.Xml (spec)" depends on "Sax (spec)"
util-serialize-io-xml.ads:22:06: file "sax.ads" not found
util-serialize-io-xml.ads:22:06: "Util.Serialize.Io.Xml (body)" depends on "Util.Serialize.Io.Xml (spec)"
util-serialize-io-xml.ads:22:06: "Util.Serialize.Io.Xml (spec)" depends on "Sax (spec)"
util-serialize-io-xml.ads:23:06: file "unicode.ads" not found
util-serialize-io-xml.ads:23:06: "Util.Serialize.Io.Xml (body)" depends on "Util.Serialize.Io.Xml (spec)"
util-serialize-io-xml.ads:23:06: "Util.Serialize.Io.Xml (spec)" depends on "Unicode (spec)"
util-serialize-io-xml.ads:24:06: file "input_sources.ads" not found
util-serialize-io-xml.ads:24:06: "Util.Serialize.Io.Xml (body)" depends on "Util.Serialize.Io.Xml (spec)"
util-serialize-io-xml.ads:24:06: "Util.Serialize.Io.Xml (spec)" depends on "Input_Sources (spec)"

   compilation of util-serialize-io-xml.adb failed

gprbuild: *** compilation phase failed
gmake: *** [Makefile:35: static] Error 4

The compiler used is gcc6-aux
`

**Comment by stcarrez** [comment]
> checking XML/Ada version... none

It looks like XML/Ada is not installed.

The build should not fail. It should build without the XML support but it looks like this is broken.

**Comment by stcarrez** [comment]
You can configure with:

`./configure --with-xmlada=no`

and the build should succeed. It will not try building the XML serialization support.

**Comment by devosalain** [comment]
This time it only seem to produce 1 minor issue, it seems i can continue,
----------------------------
bin/util_harness -l utilada: -xml util-aunit.xml -timeout 30
Usage: test <exit-code> <mode> <data>
b
c
d
e
f
  Events.Timers:
   Test Util.Events.Timers.Repeat+Process - TIMEOUT ERROR    30.00100900s
utilada:        Tests run: 266, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 38.873627000
gmake: [Makefile:63: test] Error 1 (ignored)
